[package]
name = "lv_events"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
lv_types = { path = "../lv_types" }
serde_json.workspace = true
tokio.workspace = true
